/**
 * HINENI HUB Loader v1.0
 * ======================
 * Loads hub inventory from hub-inventory.json (generated by scanner)
 * Replaces hardcoded hineni-hub.js with dynamic discovery
 * 
 * The hub knows itself because it scans itself.
 */
(function() {
    'use strict';

    // ═══════════════════════════════════════════════════════════════════
    // CONFIGURATION
    // ═══════════════════════════════════════════════════════════════════
    
    var CONFIG = {
        inventoryPath: 'hub-inventory.json',
        mountPoint: '/Volumes/HINENI_HUB',
        version: '1.0'
    };

    // Category display order and styling
    var CATEGORY_CONFIG = {
        'web-apps':      { title: '🌐 Web Apps & Games', priority: 1 },
        'toolbox-cli':   { title: '🧰 Toolbox CLI', priority: 2 },
        'macos-utils':   { title: '🍎 macOS Utilities', priority: 3 },
        'hineni-system': { title: '🧭 HINENI System', priority: 4 },
        'conflict-lab':  { title: '⚖️ Conflict Lab', priority: 5 },
        'repos':         { title: '📚 Repositories', priority: 6 },
        'docs':          { title: '📋 Documentation', priority: 7 },
        'archives':      { title: '🗄️ Archives & Packs', priority: 8 },
        'ai-infra':      { title: '🤖 AI Infrastructure', priority: 9 },
        'discovered':    { title: '🔍 Discovered', priority: 99 }
    };

    // ═══════════════════════════════════════════════════════════════════
    // STATE
    // ═══════════════════════════════════════════════════════════════════
    
    var state = {
        inventory: null,
        loaded: false,
        error: null
    };

    // ═══════════════════════════════════════════════════════════════════
    // LOADER
    // ═══════════════════════════════════════════════════════════════════
    
    function loadInventory() {
        return fetch(CONFIG.inventoryPath)
            .then(function(response) {
                if (!response.ok) {
                    throw new Error('Inventory not found. Run hub-scanner.py first.');
                }
                return response.json();
            })
            .then(function(data) {
                state.inventory = data;
                state.loaded = true;
                console.log('🧭 HINENI HUB: Loaded ' + data.items.length + ' items from inventory');
                return data;
            })
            .catch(function(err) {
                state.error = err;
                console.error('🧭 HINENI HUB: Failed to load inventory', err);
                throw err;
            });
    }

    // ═══════════════════════════════════════════════════════════════════
    // RENDERING
    // ═══════════════════════════════════════════════════════════════════
    
    function buildHref(item) {
        if (!item.path) return null;
        
        // Use pre-computed portal-relative entry if available
        if (item.entry) {
            return item.entry;
        }
        
        // HTML apps without entry field - compute relative path
        if (item.type === 'html') {
            var portalBase = '10-repos-central/CODEX-MONAD/';
            if (item.path.indexOf(portalBase) === 0) {
                return item.path.substring(portalBase.length);
            }
            return '../../' + item.path;
        }
        
        // CLI tools open terminal (handled by click handler)
        if (item.type === 'cli') {
            return '#terminal:' + (item.invoke?.command || item.name);
        }
        
        // Docs without entry field
        if (item.type === 'doc') {
            return '../../' + item.path;
        }
        
        // Folders - still use file:// as last resort (may not work)
        return 'file://' + CONFIG.mountPoint + '/' + item.path;
    }

    function createCard(item) {
        var card = document.createElement('div');
        card.className = 'portal-card hub-card';
        card.dataset.hubId = item.id;
        card.dataset.itemType = item.type || 'unknown';
        
        var statusClass = item.status === 'transcendent' 
            ? 'status transcendent' 
            : 'status active';
        
        // Add transcendent glow to card itself
        if (item.status === 'transcendent') {
            card.classList.add('hub-card-transcendent');
        }
        
        var href = buildHref(item);
        
        // Button styling based on type
        var buttonConfig = {
            'html': { icon: '🚀', text: 'Launch', class: 'app-link' },
            'cli': { icon: '💻', text: 'Terminal', class: 'app-link hub-link hub-cli-trigger' },
            'doc': { icon: '📄', text: 'View', class: 'app-link hub-link' },
            'folder': { icon: '📂', text: 'Open', class: 'app-link hub-link' }
        };
        
        var btn = buttonConfig[item.type] || buttonConfig['folder'];
        
        var linkHtml = '';
        if (href) {
            if (item.type === 'cli') {
                // CLI tools use structured invocation
                var cliInvocation = buildCliInvocation(item.invoke);
                if (cliInvocation) {
                    linkHtml = '<a href="#" class="' + btn.class + '" data-cli-command="' + escapeHtml(item.invoke?.command || '') + '" data-cli-args="' + escapeHtml((item.invoke?.argsDefault || ['--help']).join(' ')) + '">' + 
                               btn.icon + ' ' + btn.text + '</a>';
                }
            } else {
                linkHtml = '<a href="' + href + '" class="' + btn.class + '">' + 
                           btn.icon + ' ' + btn.text + '</a>';
            }
        }
        
        // Add command hint for CLI tools
        if (item.type === 'cli' && item.invoke?.command) {
            var validCmd = validateCommandToken(item.invoke.command);
            if (validCmd) {
                linkHtml += '<code class="cli-hint">$ ' + escapeHtml(validCmd) + '</code>';
            }
        }
        
        card.innerHTML = 
            '<div class="card-header">' +
                '<span class="card-icon">' + (item.icon || '📦') + '</span>' +
                '<h2 class="card-title">' + escapeHtml(item.name) + '</h2>' +
                '<span class="' + statusClass + '">' + (item.status || 'active').toUpperCase() + '</span>' +
            '</div>' +
            '<div class="card-description">' + escapeHtml(item.description || '') + '</div>' +
            '<div class="card-links">' + linkHtml + '</div>';
        
        return card;
    }

    /**
     * Validate a command token - must be a single executable name
     * Allows: alphanumeric, starting with letter/number, can contain . _ -
     */
    function validateCommandToken(cmd) {
        if (!cmd || typeof cmd !== 'string') return null;
        cmd = cmd.trim();
        // Must start with alphanumeric, can contain alphanumeric, dot, underscore, hyphen
        if (!/^[a-zA-Z0-9][a-zA-Z0-9._-]*$/.test(cmd)) return null;
        if (cmd.length > 64) return null;
        return cmd;
    }

    /**
     * Validate args array - each arg must be safe
     * Allows: alphanumeric, common flag chars (- _), no shell metacharacters
     */
    function validateArgs(args) {
        if (!args) return [];
        if (!Array.isArray(args)) {
            args = [String(args)];
        }
        return args
            .map(function(arg) {
                arg = String(arg).trim();
                // Allow: alphanumeric, dash, underscore, dot, equals (for flags like --key=value)
                if (!/^[a-zA-Z0-9._=-]+$/.test(arg)) return null;
                if (arg.length > 100) return null;
                return arg;
            })
            .filter(function(arg) { return arg !== null; });
    }

    /**
     * Build safe CLI invocation string from structured invoke object
     */
    function buildCliInvocation(invoke) {
        var command = validateCommandToken(invoke?.command);
        if (!command) return null;
        
        var args = validateArgs(invoke?.argsDefault || ['--help']);
        return command + (args.length ? ' ' + args.join(' ') : '');
    }

    /**
     * Escape HTML to prevent XSS
     */
    function escapeHtml(str) {
        if (!str) return '';
        return String(str)
            .replace(/&/g, '&amp;')
            .replace(/</g, '&lt;')
            .replace(/>/g, '&gt;')
            .replace(/"/g, '&quot;')
            .replace(/'/g, '&#39;');
    }

    /**
     * Set up event delegation for CLI tool clicks
     */
    function setupCliHandlers() {
        document.addEventListener('click', function(e) {
            var link = e.target.closest('a.hub-cli-trigger');
            if (link) {
                e.preventDefault();
                var command = validateCommandToken(link.dataset.cliCommand);
                var args = link.dataset.cliArgs || '--help';
                
                if (command && window.HINENI && window.HINENI.terminal) {
                    var invocation = command + ' ' + args;
                    window.HINENI.terminal.open(invocation);
                }
            }
        });
    }

    /**
     * Auto-register inventory tools in terminal
     * Makes `toolname` or `help toolname` work for any discovered tool
     */
    function registerToolsInTerminal() {
        if (!window.HINENI || !window.HINENI.terminal || !window.HINENI.terminal.register) {
            console.warn('HINENI HUB: Terminal not available for tool registration');
            return;
        }
        
        var registered = 0;
        
        state.inventory.items.forEach(function(item) {
            var cmdName = item.invoke?.command || item.id;
            if (!cmdName) return;
            
            // Sanitize command name
            cmdName = cmdName.toLowerCase().replace(/[^a-z0-9_-]/g, '');
            if (!cmdName) return;
            
            // Register tool in terminal
            window.HINENI.terminal.register(cmdName, function() {
                var output = [];
                output.push('<div class="term-success">');
                output.push((item.icon || '📦') + ' <strong>' + escapeHtml(item.name) + '</strong>');
                output.push('</div>');
                output.push('<div>' + escapeHtml(item.description || 'No description') + '</div>');
                output.push('<div class="term-warning">');
                output.push('Type: ' + (item.type || 'unknown'));
                output.push('</div>');
                output.push('<div>Path: ' + escapeHtml(item.path || 'N/A') + '</div>');
                
                if (item.type === 'cli' && item.invoke?.command) {
                    output.push('<div class="term-warning">');
                    output.push('Run in real terminal: $ ' + escapeHtml(item.invoke.command));
                    output.push('</div>');
                }
                
                if (item.type === 'html' && item.entry) {
                    output.push('<div class="term-success">');
                    output.push('Launch: <a href="' + item.entry + '">' + item.entry + '</a>');
                    output.push('</div>');
                }
                
                return output.join('<br>');
            });
            
            registered++;
        });
        
        console.log('🧭 HINENI HUB: Registered ' + registered + ' tools in terminal');
    }

    function createCategorySection(categoryId, items) {
        var config = CATEGORY_CONFIG[categoryId] || { title: categoryId, priority: 50 };
        
        var section = document.createElement('div');
        section.className = 'hub-category';
        section.dataset.categoryId = categoryId;
        
        var title = document.createElement('h3');
        title.className = 'hub-category-title';
        title.textContent = config.title;
        section.appendChild(title);
        
        var grid = document.createElement('div');
        grid.className = 'portal-grid';
        
        items.forEach(function(item) {
            grid.appendChild(createCard(item));
        });
        
        section.appendChild(grid);
        return section;
    }

    function render() {
        var container = document.getElementById('hineni-hub-section');
        if (!container) {
            console.warn('HINENI HUB: #hineni-hub-section not found');
            return;
        }
        
        if (!state.inventory) {
            container.innerHTML = '<div class="hub-error">Inventory not loaded. Run scanner first.</div>';
            return;
        }
        
        // Auto-register tools in terminal
        registerToolsInTerminal();
        
        // Clear existing content
        container.innerHTML = '';
        
        // Create wrapper
        var hubSection = document.createElement('div');
        hubSection.className = 'hub-section';
        
        // Header with stats
        var meta = state.inventory.meta || {};
        var stats = state.inventory.stats || {};
        
        var header = document.createElement('div');
        header.className = 'hub-section-header';
        header.innerHTML = 
            '<h2 class="hub-section-title">HINENI HUB</h2>' +
            '<div class="hub-section-subtitle">Portable Infrastructure • ' + CONFIG.mountPoint + '</div>' +
            '<div class="hub-stats">' + 
                stats.total_items + ' items • ' +
                'Scanned ' + (meta.generated ? new Date(meta.generated).toLocaleString() : 'unknown') +
            '</div>';
        hubSection.appendChild(header);
        
        // Group items by category
        var categories = {};
        state.inventory.items.forEach(function(item) {
            var cat = item.category || 'discovered';
            if (!categories[cat]) {
                categories[cat] = [];
            }
            categories[cat].push(item);
        });
        
        // Sort categories by priority
        var sortedCats = Object.keys(categories).sort(function(a, b) {
            var pa = (CATEGORY_CONFIG[a] || {}).priority || 50;
            var pb = (CATEGORY_CONFIG[b] || {}).priority || 50;
            return pa - pb;
        });
        
        // Render each category
        sortedCats.forEach(function(catId) {
            if (categories[catId].length > 0) {
                hubSection.appendChild(createCategorySection(catId, categories[catId]));
            }
        });
        
        container.appendChild(hubSection);
        
        console.log('🧭 HINENI HUB: Rendered ' + state.inventory.items.length + ' items');
    }

    // ═══════════════════════════════════════════════════════════════════
    // INITIALIZATION
    // ═══════════════════════════════════════════════════════════════════
    
    function init() {
        setupCliHandlers();  // Set up event delegation for CLI tools
        
        loadInventory()
            .then(render)
            .catch(function(err) {
                var container = document.getElementById('hineni-hub-section');
                if (container) {
                    container.innerHTML = 
                        '<div class="hub-error">' +
                        '<h3>⚠️ Hub Inventory Not Found</h3>' +
                        '<p>Run the scanner to generate inventory:</p>' +
                        '<code>python3 hub-scanner.py</code>' +
                        '<p>Or double-click START_HUB.command</p>' +
                        '</div>';
                }
            });
    }

    // Run on DOM ready
    if (document.readyState === 'loading') {
        document.addEventListener('DOMContentLoaded', init);
    } else {
        init();
    }

    // ═══════════════════════════════════════════════════════════════════
    // PUBLIC API
    // ═══════════════════════════════════════════════════════════════════
    
    window.HINENI = window.HINENI || {};
    window.HINENI.hub = {
        load: loadInventory,
        render: render,
        getInventory: function() { return state.inventory; },
        getItem: function(id) {
            if (!state.inventory) return null;
            return state.inventory.items.find(function(i) { return i.id === id; });
        },
        config: CONFIG,
        version: CONFIG.version
    };

})();
